### ISSUE TITLE
Backbone adapter

### ISSUE THREAD

**Issue by ORESoftware** [wmdmark/backbone-rivets-example#6]
Thanks for this adapter - it's 2015 and with Backbone, we are supposed to use this.listenTo(model...) instead of using this.model.on('age'...) etc.

Is there a way to change the adapter to fit the this.listenTo paradigm? It might not be needed however....------> because for views it is much more important to use this.listenTo, whereas for models, it is probably more OK to use this.on()

what do you think? thanks!

**Comment by wmdmark** [comment]
Hi @ORESoftware. Good question. For most cases (especially in views) you certainly want to use `listenTo`. In the case of this adaptor though, using `.on` is just fine since the `.off` method is being handled by rivets in the [`unsubscribe`](https://github.com/wmdmark/backbone-rivets-example/blob/master/app/example.coffee#L14) function. Hope that makes sense!
